### ISSUE TITLE
Missing TERM leads to crash

### ISSUE THREAD

**Issue by markus1189** [jtdaugherty/vty#107]
If the `TERM` env variable is not set, `vty` leads to a complete crash.  This just happened to me while trying to run a haskell program that uses brick from a docker container missing `TERM`.

The problem is that in https://github.com/coreyoconnor/vty/blob/master/src/Graphics/Vty/Config.hs#L172 there is no fallback of any kind.

**Comment by jtdaugherty** [comment]
What do you expect the behavior to be when `TERM` is missing?

**Comment by markus1189** [comment]
I am sure you know more than I ;)
Is immediately crashing without any message a good option? I think an easy
improvement would be to crash with a message saying that TERM is missing.
Then the user at least knows what's going on.

**Comment by jtdaugherty** [comment]
Absolutely! I was asking because I wasn't sure if you expected the application to be able to run without `TERM`. :) I think a more graceful exit in the absence of `TERM` makes sense, though. Feel free to submit a pull request; if you don't get time, I should be able to get to this in the next few days. Thanks!

**Comment by glguy** [comment]
I think it'd be good if we had an exception for failure to start-up VTY.

Something like:

``` haskell
data VtyError = BadConfigurationFile | MissingTerm deriving (Show)
instance Exception VtyError where
  displayException = ...
```

This would allow a careful user of VTY to gracefully handle these (and other) startup failure modes.

**Comment by markus1189** [comment]
@glguy's solution definetely is better, but I quickly put an `error` in there in #110 .  I saw that one could also forget pattern matching and use the result of `getEnv` directly as `termName`, but I don't know if that would break other parts of the code.  I am currently not able to build `vty` on NixOS, somehow the `ncurses` library is not found during the build...

**Comment by jtdaugherty** [comment]
@markus1189 Would you be willing to refactor your patch to use the approach proposed by @glguy?

**Comment by jtdaugherty** [comment]
Thanks @markus1189 and @glguy for working on this.

**Comment by jtdaugherty** [comment]
This has been released in `5.11`.

**Comment by glguy** [comment]
@jtdaugherty said:

> This has been released in 5.11.

Could you tag that in the repo?

**Comment by jtdaugherty** [comment]
I pushed a `5.11` tag; do you not see it?

**Comment by glguy** [comment]
@jtdaugherty I must have pulled from the wrong repository or something, I'm getting it now. Thanks!
