### ISSUE TITLE
Apply attribute to an empty Image?

### ISSUE THREAD

**Issue by ChrisPenner** [jtdaugherty/vty#114]
Hey there! Thanks so much for making this lib! It's the best interface for terminal interactions I've found (I know it can be really hard to work with weird terminal restrictions)

Anyways, I'm working on building a text editor and it would simplify things a lot if I could construct
empty Images that still have Attributes which I can combine with other images. I attempted this with something like this:

```haskell
import qualified Graphics.Vty as V

V.text' green "green " V.<|> V.text' blue "" V.<|> V.text' V.currentAttr "should be blue!"
            where blue = V.defAttr `V.withForeColor` V.blue
                  green = V.defAttr `V.withForeColor` V.green
```

However it seems that any attributes applied to an empty text ("") don't actually get applied (if I add a char to the text it works as expected). This appears to be because of this: https://github.com/coreyoconnor/vty/blob/master/src/Graphics/Vty/Image.hs#L99, an empty text discards the attributes and replaces it with an emptyImage.

Is there any way to have attribute markers like this without rendering a char? What I'd love to have is an emptyImage signature with an attribute slot:

```haskell
emptyImage :: Attr -> Image
```

Thanks for your time! Cheers!

**Comment by jtdaugherty** [comment]
If possible I think it would be better if we can make it so that `emptyImage` doesn't interfere with attributes this way at all. I should have some time soon to look into this if you don't. Thanks for the report!

**Comment by ChrisPenner** [comment]
I think you might be misunderstanding my intention?

The goal I have in mind is to be able to create 'spacer' images that don't add any characters, but DO change the attributes for all Images that follow (with currentAttr). This allows me to take Images that I've put together throughout my app and 'stitch' them together; applying traits to them as I see fit without needing to add an extraneous character.

For example, let's say that elsewhere I build up a list of images that correspond to lines of text I'd like to render, if for example I wanted each line to render in a different color, it would be helpful to map through the list and `(emptyImage colourAttr <|>)` onto each  Image (with a different color for each).

Maybe that's what you meant, but I figure it's worth it to clarify 😄 

Any way we can find to solve this problem is A-OK with me!

Nice work on Brick BTW!

**Comment by jtdaugherty** [comment]
> The goal I have in mind is to be able to create 'spacer' images that don't add any characters, but DO change the attributes for all Images that follow (with currentAttr). This allows me to take Images that I've put together throughout my app and 'stitch' them together; applying traits to them as I see fit without needing to add an extraneous character.
> 
> For example, let's say that elsewhere I build up a list of images that correspond to lines of text I'd like to render, if for example I wanted each line to render in a different color, it would be helpful to map through the list and (emptyImage colourAttr <|>) onto each Image (with a different color for each).

Although Vty has `currentAttr`, I'm concerned using it to manage attribute state will be brittle. Another approach would be to create the `Image` values as part of your map over the list, and at that time pass the desired attribute to `string` or whatever function(s) you're using to build the `Image`s.

At any rate my resistance to using `emptyImage` in this way is that I think it breaks the contract of `emptyImage`. That contract is that for any image `a`, `a <|> emptyImage = a` and `emptyImage <|> a = a`, i.e., removing it has no effect. But the behavior you're requesting breaks that contract, and I'd be concerned about unintended consequences. I'll argue that in general an empty image should have _no effect_ on output while an "empty image with attribute change" is not an _empty_ image because it changes the output. Does that make sense?

> Maybe that's what you meant, but I figure it's worth it to clarify 😄

Thanks for the clarification; I don't think I understood before.

> Nice work on Brick BTW!

Thanks!

**Comment by ChrisPenner** [comment]
> At any rate my resistance to using emptyImage in this way is that I think it breaks the contract of emptyImage.

Oh definitely! It breaks the Monoid's identity laws and I don't think that emptyImage should change,

Rather, what I was hoping to suggest is something very _like_ emptyImage, a `setAttrImage :: Attr -> Image` if you will, this would be implemented as a completely new image constructor that has the properties I desire.

I'm fine with not adding a new constructor if the empty text element is changed to apply its attrs, currently:  `Vty.text attr "" == Vty.emptyImage`; which isn't what I'd expect, it ignores the attr completely. 

If the text constructor were fixed to still apply the attr even when the text is empty we could simply set:

``` haskell
setAttrImage attr = Vty.text attr ""
```

And I'd be pleased as punch!

**Comment by jtdaugherty** [comment]
Would you be willing to fork `vty`, make that change locally, and test to ensure that it gives you the results that you want?

**Comment by ChrisPenner** [comment]
I can give it a try! After a cursory glance over the source it looks over like most spots that 'text' is used it assumes a non-empty text, so it might be a bit tricky. Do you have any pointers/suggestions of where to start on this?

**Comment by jtdaugherty** [comment]
I think it might just be a matter of adding a new function

```
setAttrImage :: Attr -> Image
setAttrImage a = HorizText a "" 0 0
```

but testing would be required to see what the rest of the library does with an `Image` like that. It _might_ get optimized away or not have the desired effect.

**Comment by ChrisPenner** [comment]
Sounds good, I'll give it a go when I get a chance! Thanks for you help on this, I'll likely ping you about this when I have questions if that's alright with you.

**Comment by jtdaugherty** [comment]
Okay, sounds good. Thanks!

**Comment by glguy** [comment]
Keep in mind that an EmptyImage not only has zero width, it also has zero height. On the other hand a HorizText is always considered to have one height. Assumptions about this are likely to be baked in in a few places.

**Comment by jtdaugherty** [comment]
@glguy yeah, those are exactly the kinds of things I'm concerned about with making any changes here.

**Comment by ChrisPenner** [comment]
For a quick initial test I just removed the case that coerces to emptyImage and used `text attr ""` where I need the spacer : https://github.com/coreyoconnor/vty/blob/master/src/Graphics/Vty/Image.hs#L99

Everything seem to work fine and I gain the functionality I wanted. It may be nice to have a general version that has 0 height and 0 width, but this would solve my current use-case well.

The build is currently failing on master so it was tough to see if I caused any new tests to fail, but the only one that I could see that may have been new was `twoDwHorizCat`, https://github.com/coreyoconnor/vty/blob/master/test/VerifyImageOps.hs#L32,
But seeing as how it's only related to chars, I may be mistaken on whether that's new.

At any rate, it seems like this could work, I'll take a better look when I have more time.

**Comment by ChrisPenner** [comment]
Here's a fix for this: https://github.com/coreyoconnor/vty/pull/116

**Comment by jtdaugherty** [comment]
With #116 merged, this should now be fixed. @ChrisPenner - if you agree, please close. Otherwise let me know what else I can do.

**Comment by ChrisPenner** [comment]
Thanks for taking care of cleaning this up! I wish I was able to help more, but I'm pretty unfamiliar with the lib at this point, but learning every day!

It's working fine on my end 👍
