### ISSUE TITLE
Explain Windows installation

### ISSUE THREAD

**Issue by ndmitchell** [jtdaugherty/vty#119]
I just tried to install `vty` on Windows under cygwin. The `unix` package (a dependency) won't even install. It says in the README that Windows is cygwin only. Is that something that anyone has ever got working? If so, what is the magic? If not, perhaps update the README.

**Comment by jtdaugherty** [comment]
Thanks for pointing this out! Having never tried it and being a new maintainer, I'm not entirely clear on the status of Windows support (although I do welcome contributions in this regard). There is an unfinished pull request that Corey (former maintainer) updated periodically for a while, in case you'd like to read up on the context:

https://github.com/jtdaugherty/vty/pull/1

In the mean time, though, based on your experience, I'll definitely update the README to avoid false advertising.

**Comment by jtdaugherty** [comment]
Now that the README has been updated, please close this issue if you think it has been resolved. Otherwise please let me know what else I can do.

**Comment by ndmitchell** [comment]
Thanks, that makes it clear and matches my experience.
