### ISSUE TITLE
Handle terminal suspend signal

### ISSUE THREAD

**Issue by noughtmare** [jtdaugherty/vty#120]
See https://github.com/yi-editor/yi/issues/152

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by simonmichael** [comment]
I have this working pretty well, in brick, like so:
https://github.com/simonmichael/hledger/blob/cc0764eac255edf7459c2b9ec13903a2ef51813b/hledger-ui/Hledger/UI/UIUtils.hs#L55-L88
You can suspend, resume, and after resume the screen redraws. But depending what was just drawn, the terminal attributes can be messed up while suspended (so you have to type "reset"). I'm having trouble figuring out how to reset them automatically.

**Comment by jtdaugherty** [comment]
If you use Brick's `suspendAndResume` then that will take care of that for you.

**Comment by jtdaugherty** [comment]
So you'd do something like
```haskell
unixSuspend :: s -> EventM n (Next s)
unixSuspend s = suspendAndResume $ do
  suspend
  return s
```

**Comment by jtdaugherty** [comment]
(Put another way, in `brick`, `suspendAndResume` is the *only* correct way to handle control-of-terminal changes, because it is responsible for tearing down and starting up Vty.)

**Comment by jtdaugherty** [comment]
Also, thinking about this now, I'm not quite sure how Vty can be responsible for handling suspend signals any better than it already does. Did @noughtmare have any particular expectation about how this was going to work? It seems to me that what to do in the event of such a signal really depends on the application in question, meaning that at the time of a suspend signal a clean shutdown of the current Vty handle and the creation of a new one need to be interleaved with other application concerns as appropriate.

**Comment by simonmichael** [comment]
Thanks for the quick response. I think suspendAndResume starts a new IO action so can't replicate Ctrl-Z functionality, ie suspending and returning to the original shell.

**Comment by simonmichael** [comment]
With a little more time, I see it! Slightly mind bending, but it works perfectly. Thanks @jtdaugherty !
```
-- | On posix platforms, suspend the program using the system STOP signal
-- (as control-z usually does in bash). On windows, does nothing.
#ifdef mingw32_HOST_OS
suspendSignal :: IO ()
suspendSignal = return ()
#else
import System.Posix.Signals
suspendSignal :: IO ()
suspendSignal = raiseSignal sigSTOP 
#endif

-- | On posix platforms, suspend the program using the STOP signal,
-- like control-z in bash, returning to the original shell prompt.
-- On windows, does nothing.
suspend :: s -> EventM a (Next s)
suspend st = suspendAndResume $ suspendSignal >> return st
```

**Comment by jtdaugherty** [comment]
Yeah, that's what I was thinking.
