### ISSUE TITLE
Getting the window size

### ISSUE THREAD

**Issue by ColemanGariety** [jtdaugherty/vty#121]
What is the current method of getting the window size? The changelog says that `getSize` is deprecated and to use `display_bounds <- terminal` instead, but I can't find which module `terminal` is in. Reading the source code it looks like `reserveTerminal` returns the window size, but is that the proper way to get it?

Thanks.

**Comment by jtdaugherty** [comment]
I think what you're looking for is
```
do
  vty <- mkVty defaultConfig
  ...
  displaySize <- displayBounds $ outputIface vty
  ... $ regionWidth displaySize
  ... $ regionHeight displaySize
```
Let me know if that helps; close this ticket if so, or let me know what else I can do.

**Comment by ColemanGariety** [comment]
Thanks! I found it in the `vty-examples` package.

**Comment by jtdaugherty** [comment]
Great!
