### ISSUE TITLE
docs for CLI app newbs

### ISSUE THREAD

**Issue by bonds** [jtdaugherty/vty#123]
I'm a CLI app newb looking to make his first app. I'm fond of, and slightly experienced with Haskell, and thought using a Haskell CLI library might be neat. I found the one with ncurses bindings, and then started reading an [ncurses tutorial](http://www.tldp.org/HOWTO/NCURSES-Programming-HOWTO/index.html), but I started to wonder how much going through the ncurses tutorial was going to help me with using vty. I started reading the vty docs on hackage and got the first demo working, but it feels like I'm skipping over some essential foundational material, that is to say, vty seems to assume some I have more context about building CLI apps than I have, being a newb. I looked over the docs listed at the bottom of the README, and they seem more suited to someone that wants to know how to contribute to vty or write a competing library than someone that just wants to make a CLI app with a bunch of the craziness of terminals abstracted away.

So, here I am asking for some pointers. :) A tutorial for newbs would be awesome, but would likely be time consuming to put together. Short of that, some links to docs that newbs should read would be great. Perhaps you could take a look at the ncurses intro I reference above and see if I'm on the right track, and if so add it to the README for future newbs to benefit. Or if I'm wasting my time with that, perhaps there's something else available that's already more vty friendly.

Thanks for the library and thanks for reading this feature request! Feel free to close this if its not in the cards--I will not be offended and I appreciate the consideration in any case.

**Comment by jtdaugherty** [comment]
Thanks for the request!

> So, here I am asking for some pointers. :) A tutorial for newbs would be awesome, but would likely be time consuming to put together. Short of that, some links to docs that newbs should read would be great. Perhaps you could take a look at the ncurses intro I reference above and see if I'm on the right track, and if so add it to the README for future newbs to benefit. Or if I'm wasting my time with that, perhaps there's something else available that's already more vty friendly.

On this note, it would help me to know a bit more about what would be helpful. Vty provides some demo programs in the `vty-examples` package, but it's true that we don't have much in the way of a step-by-step tutorial. There's a lot that could be meant by "newb" here, so it isn't obvious to me what you're missing that could be provided or helpful. Can you suggest some specifics?

**Comment by bonds** [comment]
Ok, here goes.

The app I aspire to make is one where the user starts typing, and as they type, a list of potential matches is shown above, filling the available window space. As they continue to type (or even if they just wait), the list updates, reflecting both background progress on their search, and the changes they've made to the search query by virtue of typing. So, a sort of autocomplete UI similar to FZF. Once they see a match they like, they can use arrow keys to highlight the desired match, and they press enter to select it and use it.

Why not just FZF? I have other plans like searching through a list of songs, both local and remote, mixing URLs and files into a single list, so I'm not just searching (local) files. Might want to do fancy stuff later, like 'previewing' the selected song after its highlighted for 5 seconds, etc.

I imagine I need to do stuff like:

* clear the screen at startup
* add a prompt at the the top, i.e. >
* handle keypress events, with enter, ctrl-c, and arrow keys getting special treatment
* when a (non-special) key is pressed, echo it and update the list of matches I might want to show
* when the list of matches changes, update the list as its displayed on the screen
* display the list of matches, filling up the available screen real estate
* redraw when the terminal window changes size, clipping or expanding the list to fit the new size
* make sure everything stays on the screen without scrolling off when new content is added
* highlight a line (for use with the arrow keys)
* use colors to highlight parts of the line that match the search term
* allow scrolling through the matches, i.e. using arrow keys, page down/up, home/end so you can access more matches than may be displayed on the screen at one time

**Comment by jtdaugherty** [comment]
What you describe goes *way* beyond what a tutorial would provide. However, `vty` *can* do what you want but a lot of boilerplate has to be written. You might consider taking a look at another library that provides a lot of the infrastructure to make your application much easier to write:

https://github.com/jtdaugherty/brick
http://hackage.haskell.org/package/brick

`brick` uses `vty` to do its terminal I/O but is higher-level. Check out the demo programs; some of them even do the kinds of things you're describing!

**Comment by simonmichael** [comment]
Also, hledger-iadd does quite a bit of this.

**Comment by jtdaugherty** [comment]
Nice! @bonds - you can look at the program @simonmichael mentioned as a detailed example of `brick` usage:

https://github.com/hpdeifel/hledger-iadd

**Comment by bonds** [comment]
Awesome, thanks for the tips! I'll checkout brick and hledger-iadd, and if I'm still lost I'll move the discussion to brick. And with that said, I suggest you link to those projects from the vty readme, to help future lost souls like myself. :) Might be neat to highlight some 'featured' projects that use vty in any case.

**Comment by jtdaugherty** [comment]
@bonds great! I have considered adding `brick` to the README, and as much as it might be nice to promote my other project, I'd rather not do it from the `vty` README because I've only recently taken over maintaining this library and I don't want to use it for advertising. Both libraries are useful at different levels of abstraction and I think it's important for users to make that decision on their own (although I'm happy to provide a pointer to `brick` if I think `vty` won't meet someone's needs).

**Comment by simonmichael** [comment]
Many people who find only vty will actually want brick, and brick users need to understand some of vty, so it's a good idea for each to at least mention the other. And these are two excellent libs, so promote away I say!
