### ISSUE TITLE
charFill with negative width constructs invalid Image

### ISSUE THREAD

**Issue by glguy** [jtdaugherty/vty#127]
charFill should check its arguments for negative sizes and either cap them at 0 or throw an error. The current behavior constructs a malformed image that causes the screen draw process to fail.

Catching the error earlier will make it easier to find the issue and fix it.

Capping the minimum value to 0 would make charFill behave like standard replicate functions.

I'm not sure what the right behavior is. Capping at 0 seems nice but I can see the case for either solution.

**Comment by jtdaugherty** [comment]
I just recently fixed a bug of this same variety, and I think there are a number of spots that don't do adequate checking for negatives throughout the `Image` manipulation process, so more checks or graceful fallback behaviors are definitely desired.

For this, capping to zero would be less annoying to deal with, but then silently capping could fail to reveal a bigger problem in the caller's code that might be worth dealing with. Capping to zero is probably more consistent with the other functions that do anything like this, and it's going to be harmless from a UI perspective. (And if it gives the wrong visual result, that should be readily apparent.)

So I'm reluctantly in favor of capping, but I could be persuaded either way. :)
