### ISSUE TITLE
Keyboard key release?

### ISSUE THREAD

**Issue by arcticmatt** [jtdaugherty/vty#129]
Is there a way to detect the release of a keyboard key (i.e. like EvMouseUp but for keys)? I've looked over the documentation and I think the answer is no, so thought I'd ask here.

**Comment by jtdaugherty** [comment]
Key up/down events are not supported in Vty - you only get key events when the key is pressed, and repeated events if it is held down (at the locally configured repeat rate). Supporting them would require using raw input mode as described at https://stackoverflow.com/questions/1409216/receiving-key-press-and-key-release-events-in-linux-terminal-applications but that approach isn't portable. Sorry!
