### ISSUE TITLE
Maybe a documentation issue: Infixes missing the surrounding ` marks

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/vty#131]
Hi! Thanks for your work. I'm working through the Snake demonstration program for Brick, which is built on Vty, and enjoying it greatly.

On this page:

http://hackage.haskell.org/package/vty-5.16/docs/Graphics-Vty-Attributes.html

the first two code blocks use withForeColor as an infix, but without the surrounding ` marks. Am I correct that those should be there?

**Comment by jtdaugherty** [comment]
You're right - they're actually there in the Haddock comments but aren't escaped as they should be. Thanks!
