### ISSUE TITLE
Linux (Ubuntu, Konsole), modifier keys, and the representation of Tab

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [jtdaugherty/vty#133]
I can't seem to use the modifier keys except for MMeta. I'm running a Brick app from within GHCI, from within Konsole, from within Kubuntu (Ubuntu distributed with KDE) version 16.04.

I'm using the `Editor` object created by the `editor` function from `Brick.Edit`. When I press, for instance, Ctrl-Enter, after setting the function so that it should treat that specially, it just drops the cursor. That's true even though I'm handling the case of Ctrl-Enter before the catch-all case for general input. The same holds for Shift, Ctrl and Alt, but Meta works:

```
appHandleEvent :: St -> T.BrickEvent Name e -> T.EventM Name (T.Next St)
appHandleEvent st (T.VtyEvent ev) =
  let focus = F.focusGetCurrent (st^.focusRing)
  in case ev of
  V.EvKey V.KEsc [] -> M.halt st
  V.EvKey (V.KChar '\t') [] -> M.continue $ st & focusRing %~ F.focusPrev
    -- TODO ? why is this the representation of Tab?
--  V.EvKey V.KEnter [V.MCtrl] -> case focus of -- nope
--  V.EvKey V.KEnter [V.MShift] -> case focus of -- nope
--  V.EvKey V.KEnter [V.MAlt] -> case focus of -- nope
  V.EvKey V.KEnter [V.MMeta] -> case focus of -- yup
    Just Edit1 -> addToRSLT st
    Just Edit2 -> viewRSLT st
  _ -> M.continue =<< case focus of
    Just Edit1 -> T.handleEventLensed st edit1 E.handleEditorEvent ev
    Just Edit2 -> T.handleEventLensed st edit2 E.handleEditorEvent ev
    Nothing -> return st
appHandleEvent st _ = M.continue st
```

Less importantly but still of interest: From (I believe) one of the Brick tutorials, I cribbed this line:

```
  V.EvKey (V.KChar '\t') [] -> M.continue $ st & focusRing %~ F.focusPrev
```

The effect is that when I press Tab, it toggles between windows. That's great -- but why is that the representation of Tab? It looks like it would be the representation of the letter 't'.

**Comment by jtdaugherty** [comment]
> I can't seem to use the modifier keys except for MMeta. I'm running a Brick app from within GHCI, from within Konsole, from within Kubuntu (Ubuntu distributed with KDE) version 16.04.

Have you tried:
 * Not running from within GHCI?
 * Using other terminal emulators?

Just so you are aware, modifier key combination support not only varies from emulator to emulator, but is often configurable - check your Konsole settings to see if there are modifiers that are disabled or mapped somehow. And be sure to try `urxvt` and `xterm`.

In my experience, modifiers with `Enter` often do not work well.

> why is that the representation of Tab? It looks like it would be the representation of the letter 't'.

Tab, like newline (`\n`) and carriage return (`\r`), has its own representation that has been used for decades. The plain letter "t" is represented using a normal character: `t`. The presence of the backslash indicates a special tab character to distinguish it from the normal character.

**Comment by jtdaugherty** [comment]
I'm going to close this since I don't think there are any Vty bugs reported here, but if that turns out to be wrong then we can just re-open. Thanks!

**Comment by JeffreyBenjaminBrown** [comment]
This is a little late :) but I might as well confirm that it works in XTerm for me.  So yeah, probably not a VTY bug. Thanks!

**Comment by JeffreyBenjaminBrown** [comment]
In fact it even works in Konsole now, unless I use tmux.  (I only learned about tmux this year, so I believe it really was a Konsole problem before, but they appear to have fixed it.)
