### ISSUE TITLE
GHC -threaded option required to build

### ISSUE THREAD

**Issue by ericnething** [jtdaugherty/vty#142]
For anyone new to this library (like me), the first time they try to compile even the simplest "hello world" program, they are confronted with this error:

```
user error (RTS doesn't support multiple OS threads (use ghc -threaded when linking))
```

The solution is to include this in your .cabal file in `ghc-options:` under your executable block, but there is no indication that this is required in any of the documentation (as far as I could find). I thought I may have done something wrong, or something was broken. I had to ask around to get an explanation, which is a terrible way to start with a new library.

I feel this needs to be added to the top of the documentation (in bold lettering) and to the installation guide. Especially since this library is self-described as "easy to use", but this obstacle knocks you down as soon as you take your first step.

**Comment by jtdaugherty** [comment]
Thanks, I just pushed a patch to comment on this in the README and the `Graphics.Vty` haddock. I've also updated the Brick User Guide similarly:

https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#compiling-brick-applications
https://github.com/jtdaugherty/vty#development-notes
