### ISSUE TITLE
Part-display outputs

### ISSUE THREAD

**Issue by rampion** [jtdaugherty/vty#143]
The `Output` generated by `Graphics.Vty.Output.TerminfoBased.reserveTerminal` clears the entire display and reserves its entire space for output.

It seems like it would be possible to generate an alternate terminfo-compatible `Output` that
- did not clear the display
- only reserved part of the display for the vty.

This would enable users to create applications that didn't dominate the entire terminal display, but used only the space necessary:

    +-before--------------+ +-during--------------+ +-after---------------+
    | $ cat food          | | rice                | | additives           |
    | fish                | | additives           | | yellow #5           |
    | chicken             | | yellow #5           | | $ ls                |
    | rice                | | $ ls                | | a.txt b.txt food    |
    | additives           | | a.txt b.txt food    | | $ pong              |
    | yellow #5           | | $ pong              | |                     |
    | $ ls                | |                     | |      YOU LOSE       |
    | a.txt b.txt food    | |                   ( | |                     |
    | $                   | | ) *                 | | $                   |
    +---------------------+ +---------------------+ +---------------------+

I'm going to try to implement this for a brick app I'm working on (with substantial copy-and-paste from `intMkVty` and `reserveTerminal`), but it'd be nice if the API supported it.

**Comment by jtdaugherty** [comment]
Let me know how that works out; I'd be open to having this in Vty if it does.

**Comment by jtdaugherty** [comment]
@rampion Did you ever make progress on this?

**Comment by jtdaugherty** [comment]
I'm going to close this due to inactivity, but please re-open if needed. Thanks!
