### ISSUE TITLE
microlens now exports `(<>~)`

### ISSUE THREAD

**Issue by dmwit** [jtdaugherty/vty#145]
As of microlens-0.4.9, `Lens.Micro` exports `(<>~)`, which clashes with `(Graphics.Vty.Input.Loop.<>~)`. (I would just fix it instead of reporting it, except that trying to build from this repo instead of Hackage gives me a bizarre dependency-solver error about `string-qq` that I'm still looking into. Sorry about that.)

**Comment by jtdaugherty** [comment]
Thanks for the report! I'll hold off on doing something about this until you have more info.

**Comment by dmwit** [comment]
More info on the `string-qq` errors [here](https://github.com/audreyt/string-qq/pull/1). Let me know if there was some other info you were waiting on.

**Comment by jtdaugherty** [comment]
Thanks!
