### ISSUE TITLE
Does nextEvent actually refresh on EvResize?

### ISSUE THREAD

**Issue by noughtmare** [jtdaugherty/vty#150]
In haddock it says:

https://github.com/jtdaugherty/vty/blob/6f4edc0228660fb407f48c070ba3cee8c7dc7615/src/Graphics/Vty.hs#L81-L82

But that is kind of misleading since that is a record which doesn't have an actual implementation. But even if I look at the implementation (given by `mkVty`):

https://github.com/jtdaugherty/vty/blob/6f4edc0228660fb407f48c070ba3cee8c7dc7615/src/Graphics/Vty.hs#L154-L158

It doesn't look like it refreshes the terminal to me.

**Comment by jtdaugherty** [comment]
Yeah, it looks like that bit of documentation is stale. It should just read
```
-- | Get an 'Event' or block until one becomes available.
```
Are you reporting this because you wanted that behavior, or just because you wanted the docs to be consistent with the current behavior?

**Comment by noughtmare** [comment]
I saw it while looking at the code for something else and I thought it was odd. 

Note that the documentation on the refresh field of the Vty record is also outdated then.

**Comment by jtdaugherty** [comment]
Okay, thanks! I've updated the docs.
