### ISSUE TITLE
How do you read out "Vty"?

### ISSUE THREAD

**Issue by typesanitizer** [jtdaugherty/vty#154]
Is it supposed to be vi-tee or vi-tie or something else?

**Comment by jtdaugherty** [comment]
It's read by spelling it out: "Vee Tee Why."

**Comment by typesanitizer** [comment]
Well, that's a bit unexpected :sweat_smile: . Do the initials stand for something? Or is like VTY because of VT1000?

**Comment by jtdaugherty** [comment]
I honestly don't know the exactly etymology of the package name, but I've always thought that it was probably related to VT100 or to TTY.

**Comment by typesanitizer** [comment]
> TTY

Ok, that makes a lot more sense now. Sorry to bore you with such trivial stuff! It's just I kept mentally vocalizing it as "V T" (I just started writing a small thing with `brick`) until I realized that might not actually be the "right" way.
