### ISSUE TITLE
verify-attribute-ops test not implemented

### ISSUE THREAD

**Issue by glguy** [jtdaugherty/vty#158]
When investigating how to fix the CI test errors I noticed that https://github.com/jtdaugherty/vty/blob/master/test/VerifyAttributeOps.hs doesn't actually test anything. Should we remove this test? Should it test something?

https://github.com/jtdaugherty/vty/blob/master/vty.cabal#L151-L169

**Comment by jtdaugherty** [comment]
Since there's not even any starter code or comments in that, I say let's remove it.
