### ISSUE TITLE
Make Graphics.Vty.shutdown idempotent

### ISSUE THREAD

**Issue by seagreen** [jtdaugherty/vty#159]
This would make it easier to write applications that ensure Vty is shut down after a crash.

Alternatively, a quick way of checking whether Vty has been shutdown would be almost as useful. I tried using `refresh`, `nextEvent`, etc, but they hang for a second and then give `thread blocked indefinitely in an MVar operation`, which isn't ideal.

**Comment by jtdaugherty** [comment]
The fix for this is now released in `5.24.1`.

**Comment by seagreen** [comment]
This is awesome, thanks!
