### ISSUE TITLE
Add a way to report whether Vty is shutdown or not

### ISSUE THREAD

**Issue by seagreen** [jtdaugherty/vty#160]
This is way less needed after https://github.com/jtdaugherty/vty/issues/159, but it would be nice in some circumstances to have an `isShutdown :: IO Bool` field on `Vty`.

I realize this would be a breaking change, but I'm curious what you think about it (and would be happy to make a PR if you do want it).

**Comment by jtdaugherty** [comment]
How would it be a breaking change?

**Comment by seagreen** [comment]
I was thinking that the only way to implement it would be adding a field to `Vty`, and that adding fields is a breaking change. Either of those assumptions might be wrong though:)

**Comment by jtdaugherty** [comment]
I'm inclined to think that adding a field should be fine here, because nobody should be pattern-matching on the fields of a `Vty` value. In other words, I think the risk of breakage is extraordinarily small. Still, bumping the version to `5.25` is cheap enough that it would be fine to do that, too.

**Comment by jtdaugherty** [comment]
As far as the actual proposal here, I'd be fine with the change you describe and it would just close over the `TVar` I added in the previous patch. If you want to submit a patch, that's great; otherwise I can get to it later today.

**Comment by seagreen** [comment]
I took a stab at it here: https://github.com/jtdaugherty/vty/pull/161

**Comment by jtdaugherty** [comment]
That looks good; I have one request, which is to remove the version bump and changelog entry. Bumping the version in the relevant patch can be a good idea, but I save that for release time, when I diff the changes since the last release and decide then what the appropriate version change is, and also write the changelog entries, collect ticket references, etc.

**Comment by seagreen** [comment]
Absolutely! (force-pushed)

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
This is now released in `5.25`.
