### ISSUE TITLE
Ambiguous occurrence ‘-~’

### ISSUE THREAD

**Issue by Mikolaj** [jtdaugherty/vty#163]
See https://travis-ci.org/AllureOfTheStars/Allure/jobs/450191623#L824

Probably a conflict with a new microlens.

**Comment by jtdaugherty** [comment]
Thanks for the report! I've revised the metadata for the latest few releases of Vty on Hackage so they bound `microlens` to avoid this. I've also released my other fix (8f32f8ea4c4b70b31b15cbe21ab9890108cd4765) in `5.25.1` on Hackage.

**Comment by Mikolaj** [comment]
Thank you! It works for me now.
