### ISSUE TITLE
Brick issue #197 seems to be related to VTY instead of to brick.

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/vty#165]
This code:

```
drawCard :: Card -> Widget n
drawCard c@(Card suit _) =
    border $ withAttr (suitAttr suit) $ str $ prettyCard c
```

produces this output:

![out](https://user-images.githubusercontent.com/3521180/48576746-9ea50500-e915-11e8-9841-813fe2b36117.png)

This seems wrong. A border should not style the border of another widget.

**Comment by jtdaugherty** [comment]
Thanks for the report! As I mentioned on the other issue, since I couldn't reproduce this behavior, it would be really helpful to me if you could provide an example of `vty` usage (no `brick` code) that reproduces this problem for you.

**Comment by NorfairKing** [comment]
@jtdaugherty Oh dear, I've never used raw vty and I cannot justify spending the time there either. I'm also not convinced that the problem doesn't lie with brick's handling of widgets and borders and styles, but you're the expert there so I'll trust your opinion.

**Comment by jtdaugherty** [comment]
Okay. In that case, we seem to be at a bit of an impasse. If something changes and you can provide a test case that reproduces this behavior for you (or point me at a complete program that does, instead), please re-open this. Thanks!
