### ISSUE TITLE
Misleading haddock comment

### ISSUE THREAD

**Issue by Mikolaj** [jtdaugherty/vty#170]
https://hackage.haskell.org/package/vty-5.25.1/docs/Graphics-Vty-Output.html#v:setCursorPos

says "column and row", but the code has the reverse "x y".

**Comment by jtdaugherty** [comment]
I'm not sure what problem you're referring to. The code does indeed use `x` for the column, and `y` for the row, and the ensuing comparison is consistent:
```haskell
(x >= 0 && x < regionWidth bounds && y >= 0 && y < regionHeight bounds)
```

**Comment by Mikolaj** [comment]
Hah, I got it mixed up  The error was in my head, not in the haddock comment. Thank you. :) Closing.

**Comment by jtdaugherty** [comment]
Okay, thanks - no problem!
