### ISSUE TITLE
Bright colors printed as non-bright

### ISSUE THREAD

**Issue by mnn** [jtdaugherty/vty#171]
![Selection_050](https://user-images.githubusercontent.com/1975567/56466801-c80f1300-6416-11e9-9647-41fa3f50b305.png)

```hs
module Main where

import Lib
import Graphics.Vty

main = do
   cfg <- standardIOConfig
   vty <- mkVty cfg
   let line0 = string (defAttr `withForeColor` green `withBackColor` brightGreen) "first line"
       line0d = string defAttr " <- green on brightGreen"
       line1 = string (defAttr `withForeColor` brightBlack `withBackColor` black) "second line"
       line1d = string defAttr " <- brightBlack on black"
       img = line0 <|> line0d <-> line1 <|> line1d
       pic = picForImage img
   update vty pic
   e <- nextEvent vty
   shutdown vty
   print ("Last event was: " ++ show e)
```

Terminal emulator is Terminology 1.2.1 and it supports bright colors (screenshot of `colortest-16`):
![Selection_049](https://user-images.githubusercontent.com/1975567/56466806-e83ed200-6416-11e9-9733-ac202da6b500.png)

Library version is 5.25.1 (I am using Stack).

**Comment by jtdaugherty** [comment]
Thanks for the report! What produced the second image?

**Comment by mnn** [comment]
It's `colortest-16` from `colortest` package in Ubuntu. I wasn't able to find exact same version online, so here's a gist - https://gist.github.com/mnn/f8a6e2b1b3e938f08cd2ebce36f85d28.

**Comment by jtdaugherty** [comment]
Thanks. Have you reproduced this with any other terminal emulators?

**Comment by mnn** [comment]
I am experiencing same issue with konsole and xterm. gnome-terminal is ok. All of them render the colortest-16 correctly.

![Selection_051](https://user-images.githubusercontent.com/1975567/56473326-1699cd00-646a-11e9-841d-9669898c8fa7.png)
From top: terminology, konsole, xterm, gnome-terminal (white is mapped to green, it's not a bug)

**Comment by glguy** [comment]
While my color scheme is solarized and things look a little different than you might expect, vty successfully distinguishes the bright and non-bright colors on Terminal.app. What TERM value are you using?

When I'm using `TERM=xterm-256color` I get the following image:

<img width="293" alt="Screen Shot 2019-04-25 at 2 18 08 PM" src="https://user-images.githubusercontent.com/12164/56769124-2284d800-6765-11e9-824e-5d28c560b39a.png">

When I'm using `TERM=xterm`, however, I get:

<img width="301" alt="Screen Shot 2019-04-25 at 2 21 06 PM" src="https://user-images.githubusercontent.com/12164/56769219-637cec80-6765-11e9-903f-c55044d962a9.png">

**Comment by mnn** [comment]
Yes, `TERM=xterm` seems to be the cause. According to [this](https://unix.stackexchange.com/a/23789) it is not possible in many terminal emulators to get info about supported colors. [Script](https://gitlab.com/victor-engmark/xterm-color-count) from comments returns in terminology with default settings `8`. After enabling option `Set TERM to xterm-256color` bright colors work.

Is is possible in vty enforce using 16 colors (ignoring `TERM` env var)?

**Comment by jtdaugherty** [comment]
@mnn It is possible to force Vty into 16-color mode:
```haskell
vty <- mkVty defaultConfig
let vty16ColorMode = vty { outputIface = (outputIface vty) { contextColorCount = 16 } }
```

**Comment by jtdaugherty** [comment]
I'm going to close this due to inactivity, but please re-open this or file a more specific issue if needed. Thanks!
