### ISSUE TITLE
Change cursor shape

### ISSUE THREAD

**Issue by Yvee1** [jtdaugherty/vty#184]
This is more a question than an issue maybe, but would it be possible to add functionality for changing the cursor shape? I know that vim changes the cursor shape, and that various escape codes exist for doing this (see [this vim wiki](https://vim.fandom.com/wiki/Change_cursor_shape_in_different_modes))

**Comment by jtdaugherty** [comment]
I'm not sure how easy that would be. The main thing to consider in adding this to Vty is terminal compatibility. One way that can be evaluated is by figuring out whether the thing you want to do (in this case, change cursor style) is specified as a `terminfo` capabillity. That way, Vty can consult the terminfo database for your terminal type to determine the right escape to use. This is how Vty's `TerminfoBased` backend works.

After looking around, I can't determine whether cursor style escapes tend to be specified in `terminfo`. (It appears that the answer is "they don't.") The page from the Vim wiki suggests that there is a more or less unique way to implement the feature for each terminal emulator in existence. :(

I like this idea, and I'd like to keep this open in case you or anyone else can point to resources that talk about how this might be implemented. For future reference:

https://pubs.opengroup.org/onlinepubs/007908799/xcurses/terminfo.html

**Comment by jtdaugherty** [comment]
I'm not sure how to interpret your "thumbs up," @Yvee1 - but I don't think there is anything else that can be done on this ticket so I'm going to close it.
