### ISSUE TITLE
Expose API to check for italic and strikethrough support

### ISSUE THREAD

**Issue by jtdaugherty** [jtdaugherty/vty#192]
It would be helpful if users can ask Vty whether the terminal connected to a `Vty` handle provides support for italics and strikethrough. Those are driven by the presence of terminal capabilities in `terminfo`, so we can expose a check for those. The documentation should note that even the presence of capabilities does not guarantee that either font style will render correctly or be supported by the terminal emulator.

**Comment by jtdaugherty** [comment]
@glguy If you want to try this out, it's ready: https://github.com/jtdaugherty/vty/commit/bcbf7fabc175353fc90e51c547bc2a4ffb24a39c

**Comment by glguy** [comment]
Thanks, I'll do that today!

**Comment by jtdaugherty** [comment]
The API I added for this ticket is now released in 5.32.
