### ISSUE TITLE
Missing Meta-modified Page Up and Page Down

### ISSUE THREAD

**Issue by glguy** [jtdaugherty/vty#193]
These keys are bound by vty.

I'm correcting it locally with `~/.vty/config`

```
map "xterm-256color" "\ESC\ESC[5~" KPageUp [MMeta]
map "xterm-256color" "\ESC\ESC[6~" KPageDown [MMeta]
```

which is working for me in iTerm2.

**Comment by jtdaugherty** [comment]
Thanks, this should be fixed now on `master`.

**Comment by jtdaugherty** [comment]
I think the correct way of fixing this would have been to look for `\ESC` followed by the `knp` or `kpp` capability strings, but I haven't looked into what that would take. So for now I just hard-coded these cases.
