### ISSUE TITLE
Support setting cursor style to vertical bar

### ISSUE THREAD

**Issue by sullyj3** [jtdaugherty/vty#221]
Some terminals support escape sequences for switching the cursor from a block to a vertical bar. It would be handy to support this!

**Comment by jtdaugherty** [comment]
Do you happen to know any details about how this is supported? In order to consider adding this to Vty, I need to understand how widespread support for this is, and I'll also need to know whether it's detectable (e.g. in `terminfo`) and how it behaves in terminals that don't support it.

**Comment by jtdaugherty** [comment]
I realized this is a duplicate of #243, essentially, so I'm going to close it.
