### ISSUE TITLE
Numbering of ISOColor's by Haddock.

### ISSUE THREAD

**Issue by KommuSoft** [jtdaugherty/vty#222]
The rendered documentation starts number from 1 as we can see [here](https://hackage.haskell.org/package/vty-5.33/docs/Graphics-Vty-Attributes-Color.html#t:Color). Perhaps it is worth to add the real value (for example between brackets).

https://github.com/jtdaugherty/vty/blob/fa74b0ae1ca2883e9c4fbfe55abc9253dc7b9841/src/Graphics/Vty/Attributes/Color.hs#L61-L75

**Comment by jtdaugherty** [comment]
That makes sense to me, thanks for spotting that!

**Comment by KommuSoft** [comment]
> That makes sense to me, thanks for spotting that!

I also created an issue in the Haddock repository (https://github.com/haskell/haddock/issues/1406), and apparently this will be fixed by haddock itself.

**Comment by jtdaugherty** [comment]
Oh, great!

**Comment by jtdaugherty** [comment]
This is now fixed and will go out in an upcoming release. Thanks!
