### ISSUE TITLE
Convert colors to a pattern synonym.

### ISSUE THREAD

**Issue by KommuSoft** [jtdaugherty/vty#223]
https://github.com/jtdaugherty/vty/blob/fa74b0ae1ca2883e9c4fbfe55abc9253dc7b9841/src/Graphics/Vty/Attributes/Color.hs#L101-L120

Perhaps it is worth to define these colors as pattern synonyms. That way these can both be used as pattern, and as expression.

**Comment by jtdaugherty** [comment]
I mentioned this on the PR, but to be explicit here, too: I'd rather avoid pattern synonyms. I don't view this code as being risky enough at present to warrant a change. Thanks for opening this and proposing it, though.
