### ISSUE TITLE
Why is `Eq v` necessary for the `Semigroup` and `Monoid` for the `MaybeDefault` datatype

### ISSUE THREAD

**Issue by KommuSoft** [jtdaugherty/vty#226]
I'm wondering why we need as type constraint `Eq v` for the instances of `Semigroup` and `Monoid`. While we will likely eventually need the `Eq` instance, at the instance level of `Semigroup` and `Monoid`, we do not make use of any function that is defined in `Eq`.

https://github.com/jtdaugherty/vty/blob/fe501ccf2716826bf6ea05a666bbcfab36631ca6/src/Graphics/Vty/Attributes.hs#L154-L163

**Comment by jtdaugherty** [comment]
It turns out we don't! Those constraints are redundant, probably made so by some recent changes. I removed them in abf7fc4cd7d7a2fd69510743c62bff99e42a2541 just now. Thanks for mentioning this!
