### ISSUE TITLE
Problems Building

### ISSUE THREAD

**Issue by patrickaldis** [jtdaugherty/vty#252]
Was just trying out the library, but was having a few problems building the `examples` package. I've built with ghc 8.4.4, 9.0.2, 9.2.4, and head, but with no luck - all seem to throw a lot of errors about `def`.

```
Rogue.hs:46:18: error:
    • No instance for (data-default-class-0.1.2.0:Data.Default.Class.Default
                         Config)
        arising from a use of ‘def’
    • In the first argument of ‘mkVty’, namely ‘def’
      In a stmt of a 'do' block: vty <- mkVty def
      In the expression:
        do vty <- mkVty def
           level0 <- mkLevel 1
           let world0 = World (Player (levelStart level0)) level0
           (_finalWorld, ()) <- execRWST play vty world0
           ....
   |
46 |     vty <- mkVty def
   |                  ^^^
```

I was wondering if I was missing something obvious.

Thanks for any help

**Comment by jtdaugherty** [comment]
What version of `vty` are you attempting to build? A Hackage release? (And if so, which one?) Or `master`?

**Comment by jtdaugherty** [comment]
@patrickaldis I'd like to get this resolved. It's been a while since this was opened; is it still a blocker for you?
