### ISSUE TITLE
List of problems with EventEcho on windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [jtdaugherty/vty#261]
`EventEcho` demo program in `vty-crossplatform`, built on win10+windows terminal, ghc-9.4.5 (lts-21.5)

- no mouse events (clicks or moves, but we can ignore moves for now); should be fixable by an additional flag in https://github.com/chhackett/vty-windows/blob/084d57abf7c2c2c9033150b630e3f3bfbfe00d2a/src/Graphics/Vty/Platform/Windows/Input.hs#L169
- presses on control keys (Ctrl/Alt/Shift) are all reported as `Ctrl+@` (maybe that's by design, I'll check the behavior of that demo on linux tomorrow); it seems off anyway
- F-keys are not parsed; should be just a matter of plugging proper parsers that were implemented in the previous iteration
- `Enter` is not seen; should be fixable by a special entry in `specialSupportKeys`
I strongly suspect that these issues are purely on the vty-windows side.

 @chhackett, what do you prefer? One big pull-request or multiple small pull-requests?

**Comment by chhackett** [comment]
Thanks for jumping in! I guess I'd prefer smaller pull requests.
I plan on adding tests to vty-windows in the next week or two.

**Comment by ShrykeWindgrace** [comment]
On linux: same dev tools and repo versions, debian11+st+tmux (or debian11+konsole):
- no mouse events reported at all; I guess that comes from vty-unix, can not attest to that
- control keys are not reported at all; my intuition says that this is the correct behavior
- F-keys reporting is inconsistent across environments; e.g. Ctrl+F4 is not parsed at all under my `konsole`:
```
-- konsole (xterm-256color)
EvKey (KFun 29) []       -- that's Ctrl+F5
EvKey (KChar 'S') []     -- and that's Ctrl+F4
EvKey (KChar '2') []     
EvKey (KChar 'O') [MMeta]
```
```
-- st+tmux (tmux-256color)
EvKey (KFun 29) []       -- that's Ctrl+F5
EvKey (KFun 28) []     -- and that's Ctrl+F4
```
@jtdaugherty is that the intended behavior for the unix version? I'll test `vty/master` some time later.

**Comment by jtdaugherty** [comment]
Frankly I have no idea, and terminal input is a mess so I wouldn't be surprised if the behavior you're seeing is in some sense "right." Modifier key support is especially spotty (not because of `vty`, but because of how keys are encoded in the terminal protocol). If you're willing, I'd be curious to see what those particular test cases above do on the `master` implementation of the event echo program. I suspect they'll be the same (i.e. I don't think the `vty-unix` split has changed behavior.)

**Comment by ShrykeWindgrace** [comment]
@jtdaugherty I agree,  pretty sure that the behavior would be the same. I'll test next week, I am on windows till at least Monday.

**Comment by chhackett** [comment]
I'd like to note that I've checked in some changes to vty-windows. I believe the issues @ShrykeWindgrace identified here have been resolved, along with improving VT input parsing/handling overall. If Shryke agrees, I think we can close this issue.

**Comment by ShrykeWindgrace** [comment]
Yep, @chhackett fixed these issues, thanks!
