### ISSUE TITLE
vty-mode-demo

### ISSUE THREAD

**Issue by ShrykeWindgrace** [jtdaugherty/vty#262]
We could bring this demo back to the vty-crossplatform

**Comment by jtdaugherty** [comment]
If you are referring to [this](https://github.com/jtdaugherty/vty/blob/master/demos/ModeDemo.hs), then it would first need to be updated to not assume a Posix environment. Assuming that's feasible (I haven't looked closely at the source), then yeah, this could be a nice demo program to move over to the cross-platform package with the others.

**Comment by jtdaugherty** [comment]
Hah, I just looked and some of the imports for Posix aren't even used! So maybe it's already basically ready.

**Comment by ShrykeWindgrace** [comment]
Yes, that's the one. I just checked, on windows it works out of the box with very minor modifications.

That being said, toggling mouse event does not work yet=) 

I'll submit a PR for the demo itself, and fixes will go to the vty-windows, I guess.

**Comment by ShrykeWindgrace** [comment]
I guess this issue is no longer relevant - https://github.com/jtdaugherty/vty-crossplatform/pull/1 is merged.
