### ISSUE TITLE
Support FocusIn/FocusOut

### ISSUE THREAD

**Issue by glguy** [jtdaugherty/vty#264]
I've started using [FocusIn/FocusOut](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-FocusIn_FocusOut) events in another of my terminal clients and was thinking it'd be pretty handy to use this in my VTY application.

* Enable: `\ESC[?1004h`
* Disable: `\ESC[?2004h`
* FocusIn: `\ESC[I`
* FocusOut: `\ESC[O`

I haven't figured out how to detect if the terminal supports this event, yet.

**Comment by jtdaugherty** [comment]
Awesome. There is also [this](https://github.com/jtdaugherty/vty/commit/4bcebb1bfe3baceba80f10d22a35dc66cc2c35ad) - have you tried that out? It looks like it uses the same sequences that you posted above.

**Comment by glguy** [comment]
Look like I just don't know what vty can do! Thanks for the pointer.

**Comment by jtdaugherty** [comment]
I haven’t used that mode very much at all, so I’d love to hear if it works in your application!
