### ISSUE TITLE
Problem updating to brick 2

### ISSUE THREAD

**Issue by locallycompact** [jtdaugherty/vty#272]
Hi I don't see a changelog entry for what happened to these symbols. How do I fix this?

```
test/Hydra/TUISpec.hs:23:3: error:
    Module ‘Graphics.Vty’ does not export ‘outputFd’
   |
23 |   outputFd,
   |   ^^^^^^^^

test/Hydra/TUISpec.hs:24:3: error:
    Module ‘Graphics.Vty’ does not export ‘outputForConfig’
   |
24 |   outputForConfig,
   |   ^^^^^^^^^^^^^^^

test/Hydra/TUISpec.hs:27:3: error:
    Module ‘Graphics.Vty’ does not export ‘termName’
   |
27 |   termName,
   |   ^^^^^^^^

test/Hydra/TUISpec.hs:30:3: error:
    Module
    ‘Graphics.Vty.Platform.Unix’
    does not export
    ‘inputForConfig’
   |
30 |   inputForConfig
   |   ^^^^^^^^^^^^^^
```

**Comment by ShrykeWindgrace** [comment]
@locallycompact 
Which version of `vty` are you using here? If it is `>=6.0`, then take a look at https://github.com/jtdaugherty/vty/blob/master/CHANGELOG.md#60 that refactoring indeed changed a lot of imports and exports.

**Comment by locallycompact** [comment]
I have read the changelog. There's no mention of `inputForConfig`.

**Comment by jtdaugherty** [comment]
Hi @locallycompact - here are the details:
* `outputFd` and `termName` got a `settings` prefix as part of being moved to the `UnixSettings` type and are now exported by `Graphics.Vty.Platform.Unix.Settings` in `vty-unix`.
* `outputForConfig` is now platform-specific and is exported by `vty-unix` as `buildOutput`, although in most cases it should not be used.
* `inputForConfig` is now platform-specific and is exported by `vty-unix` as `buildInput`, although in most cases it should not be used.

I'll update the changelog!

**Comment by jtdaugherty** [comment]
Changelog updated in ab480e74417fe51172a7b97e644f15c3952aa16a.
