### ISSUE TITLE
Missing XTerm key sequences

### ISSUE THREAD

**Issue by coreyoconnor** [jtdaugherty/vty#3]
<pre>
     -- To learn the character sequence your terminal uses, run "cat" and hit the keys. You should see the escape sequence.
       -- For example, hitting Ctrl+Home under Konsole (a variant of XTerm) might look like:
       -- $ cat
       -- ^[[1;5H
       spec KEsc ?>> char '[' ?>> char 'F' ?>>! moveToEol, -- see /usr/local/etc/joe/joerc, eol, "^[ [ F".
       spec KEsc ?>> char '[' ?>> char 'H' ?>>! moveToSol, -- home, "^[ [ H".
       spec KEsc ?>> char '[' ?>> char '1' ?>> char ';' ?>> char '5' ?>> char 'H' ?>>! topB, -- Ctrl + Home
       spec KEsc ?>> char '[' ?>> char '1' ?>> char ';' ?>> char '5' ?>> char 'F' ?>>! botB, -- Ctrl + End
</pre>

cf. http://thread.gmane.org/gmane.editors.yi.devel/2789

<pre>
ctrlCh 'h' ?>>! deleteSel bdeleteB, -- Backspace under xterm
</pre>

corresponding entry from joerc:

<pre>

backs           ^?              Backspace
backs           ^H

</pre>

**Comment by hramrach** [comment]
Hello,

I am missing these:

TERM=rxvt-unicode (urxvt)

Ctrl-Up ^[Oa
Ctrl-Down ^[Ob
Ctrl-Left ^[Oc
Ctrl-Right ^[Od

btw these are some others
^[[A Up (working)
^[[a Shift-Up (unknown)
^[^[[A Alt-Up (unknown)
