### ISSUE TITLE
Implement screen scrolling if the terminal supports it

### ISSUE THREAD

**Issue by Yuras** [jtdaugherty/vty#34]
While playing with my toy text editor, based on vty, I found that it is significantly slower compared to vim when scrolling forward/backward. Looks like vim uses special escape characters to scroll screen. AFAIK vty doesn't support it yet.

I added new function into "Vty", it does scrolling via "Terminfo.runTermOutput" and "Terminfo.scrollForward" and updates "display_ops", so that the next "update" will compare it with the new picture and output only the last line.
The speedup was up to 10x. 
(That solution is ad-hoc, that is why I didn't open pull request)

Here is a test case:

```
import Control.Monad
import Graphics.Vty as Vty

main :: IO ()
main = do
  vty <- Vty.mkVty
  forM_ [0..20] $ \i -> do
    Vty.scroll vty          -- that is the function I added to Vty
    Vty.update vty $ Vty.pic_for_image (Vty.vert_cat $ map (\j -> Vty.string Vty.def_attr $ show j) [i..i+30])
  Vty.shutdown vty
```

**Comment by jtdaugherty** [comment]
This ticket is stale, although the described functionality sounds worthwhile. I don't have time to address it, but if anyone wants to contribute it, we can re-open.
