### ISSUE TITLE
Vty does not transform a Color240 to an appropriate color. The default color is used instead.

### ISSUE THREAD

**Issue by coreyoconnor** [jtdaugherty/vty#44]
From: https://github.com/yi-editor/yi/issues/514

There is no equation for mapping the 240 palette down to the 16 or 8 palette. Some code I copied from xterm for the rgb_color can be adopted to make similar reduction operators.

Not sure why it displays nothing tho... I thought it would fall back to default colors.

**Comment by jtdaugherty** [comment]
Closing due to age/inactivity.
