### ISSUE TITLE
Types.renderBS should recognize line breaks

### ISSUE THREAD

**Issue by coreyoconnor** [jtdaugherty/vty#5]
From Simon Michael: "I expected renderBS to convert a multiline string into an Image of height > 1."

**Comment by jtdaugherty** [comment]
I notice that

* `renderBS` is now `utf8Bytestring`
* `string` and `text` also lack the above described behavior

For instance, to render a multiline string I essentially always do
```
vertCat $ string <$> lines s
```
Do you think this change is worth making? Given my experience with `vty-ui` and `brick` I'd say it would be useful to make the string-rendering functions handle newlines in a reasonable way, but it could also be a breaking change.

**Comment by jtdaugherty** [comment]
(Also, given the lack of other requests for this behavior, it could also be reasonable to just close this as unimportant.)
