### ISSUE TITLE
Use terminfo-hs instead of terminfo where reliable

### ISSUE THREAD

**Issue by coreyoconnor** [jtdaugherty/vty#82]
The package terminfo is reliable but annoying to install and use. The platform specific terminfo library needs to also be installed in addition to the haskell build process being aware of the library (#65).

An alternative is using a pure-haskell terminfo library. One that does not require the platform specific terminfo library:
- http://hackage.haskell.org/package/terminfo-hs

**Comment by jtdaugherty** [comment]
Realistically speaking, I am not going to get around to this so I'm closing it to avoid staleness. If someone becomes interested in contributing this, we can re-open.

**Comment by no-identd** [comment]
You might want to reopen this issue even with no interested contributors, due to the fact that terminfo seems to suffer from licensing inconsistency:

https://github.com/judah/terminfo/issues/6

**Comment by glguy** [comment]
It doesn't look like the mismatch between BSD2 and BSD3 in the license file and cabal file is a reason for vty need to worry about switching.

**Comment by judah** [comment]
FYI, I have released a new version (`terminfo-0.4.1.3`) which is consistently licensed under BSD3.  I apologize for the previous licensing inconsistency.
