### ISSUE TITLE
Support non-blocking input

### ISSUE THREAD

**Issue by eigengrau** [jtdaugherty/vty#87]
It would be convenient if Vty offered something to poll an event without blocking, like this:

```
tryNextEvent ∷ Vty → IO (Maybe Event)
```

I’ve found myself wanting this when drawing an animation, where a frame shouldn’t be blocked on keyboard input if nothing is there. For now, I hand-rolled this using `tryReadTChan`, but maybe it would be useful for others as well.

**Comment by glguy** [comment]
I think that the best outcome here would just be to make TChan part of the official interface to getting input. Then we could locally define whatever sort of access we need. For my part I use the TChan directly in combination with STM's registerDelay operation to handle the integration of timers with user-input in my event loop.
